import '../models/member_model.dart';

final List<Member> members = [
  Member(
    nama: 'Adeline Wijaya',
    namaPanggilan: 'Delynn',
    tanggalLahir: '1 September 2007',
    golonganDarah: 'B',
    horoskop: 'Virgo',
    tinggiBadan: '167 cm',
    image: 'asset/members/adeline.jpg',
  ),
  Member(
    nama: 'Abigail Rachel',
    namaPanggilan: 'Arcie',
    tanggalLahir: '6 December 2006',
    golonganDarah: 'O',
    horoskop: 'Sagittarius',
    tinggiBadan: '165 cm',
    image: 'asset/members/abigail.jpg',
  ),
  Member(
    nama: 'Alya Amanda',
    namaPanggilan: 'Alya',
    tanggalLahir: '21 August 2007',
    golonganDarah: 'O',
    horoskop: 'Leo',
    tinggiBadan: '160 cm',
    image: 'asset/members/alya.jpg',
  ),
  Member(
    nama: 'Amanda Sukma',
    namaPanggilan: 'Amanda',
    tanggalLahir: '21 April 2008',
    golonganDarah: 'A',
    horoskop: 'Taurus',
    tinggiBadan: '163 cm',
    image: 'asset/members/amanda.jpg',
  ),
  Member(
    nama: 'Angelina Christy',
    namaPanggilan: 'Christy',
    tanggalLahir: '5 December 2005',
    golonganDarah: 'O',
    horoskop: 'Sagittarius',
    tinggiBadan: '163 cm',
    image: 'asset/members/angelina.jpg',
  ),
  Member(
    nama: 'Anindya Ramadhani',
    namaPanggilan: 'Anin',
    tanggalLahir: '28 March 2006',
    golonganDarah: 'A',
    horoskop: 'Aries',
    tinggiBadan: '165 cm',
    image: 'asset/members/anindya.jpg',
  ),
  Member(
    nama: 'Aurellia',
    namaPanggilan: 'Lia',
    tanggalLahir: '12 July 2007',
    golonganDarah: 'O',
    horoskop: 'Cancer',
    tinggiBadan: '162 cm',
    image: 'asset/members/aurellia.jpg',
  ),
  Member(
    nama: 'Aurhel Alana',
    namaPanggilan: 'El',
    tanggalLahir: '14 October 2008',
    golonganDarah: 'B',
    horoskop: 'Libra',
    tinggiBadan: '160 cm',
    image: 'asset/members/aurhel.jpg',
  ),
  Member(
    nama: 'Catherina Vallencia',
    namaPanggilan: 'Cathy',
    tanggalLahir: '16 September 2006',
    golonganDarah: 'O',
    horoskop: 'Virgo',
    tinggiBadan: '165 cm',
    image: 'asset/members/catherina.jpg',
  ),
  Member(
    nama: 'Cathleen Nixie',
    namaPanggilan: 'Nixie',
    tanggalLahir: '28 May 2008',
    golonganDarah: 'A',
    horoskop: 'Gemini',
    tinggiBadan: '160 cm',
    image: 'asset/members/cathleen.jpg',
  ),
  Member(
    nama: 'Celline Thefani',
    namaPanggilan: 'Celline',
    tanggalLahir: '17 April 2007',
    golonganDarah: 'O',
    horoskop: 'Aries',
    tinggiBadan: '164 cm',
    image: 'asset/members/celline.jpg',
  ),
  Member(
    nama: 'Chelsea Davina',
    namaPanggilan: 'Chelsea',
    tanggalLahir: '11 December 2006',
    golonganDarah: 'B',
    horoskop: 'Sagittarius',
    tinggiBadan: '162 cm',
    image: 'asset/members/chelsea.jpg',
  ),
];